// Generated by CoffeeScript 1.10.0
'use strict';
var EventEmitter, React, ReactDom, ReactDomServer, createRootOptions, createSubOptions, delegate, rootComponent, subComponent;

EventEmitter = require('events').EventEmitter;

delegate = require('dom-delegate');

React = require('react');

ReactDom = require('react-dom');

ReactDomServer = require('react-dom/server');

rootComponent = {
  getChildContext: function() {
    if (!this.context.root) {
      this.context.root = this;
      this.isTopLevelRootComponent = true;
    }
    return {};
  },
  componentWillMount: function() {
    var events, key, results, val;
    events = {};
    if (this.events.sub) {
      events = this.events.sub;
    }
    if (this.events.pubsub) {
      events = this.events.pubsub;
    }
    if (this.events.subscribe) {
      events = this.events.subscribe;
    }
    results = [];
    for (key in events) {
      val = events[key];
      results.push(this._pubsub.on(key, val.bind(this)));
    }
    return results;
  },
  componentWillUnmount: function() {
    return this._pubsub.removeAllListeners();
  }
};

subComponent = {
  contextTypes: {
    root: React.PropTypes.object
  },
  childContextTypes: {
    root: React.PropTypes.object
  },
  getChildContext: function() {
    if (this.isRootComponent) {
      return {
        root: this
      };
    } else {
      return {
        root: this.context.root
      };
    }
  },
  componentDidMount: function() {
    var events, key, ref, results, selector, type, val;
    this._domEventDelegate = delegate(this.find());
    events = this.events.dom ? this.events.dom : this.events;
    results = [];
    for (key in events) {
      val = events[key];
      ref = key.split(';'), type = ref[0], selector = ref[1];
      if (selector) {
        results.push(this._domEventDelegate.on(type, selector, val.bind(this)));
      } else {
        results.push(this._domEventDelegate.on(type, val.bind(this)));
      }
    }
    return results;
  },
  componentWillUnmount: function() {
    if (this._domEventDelegate) {
      this._domEventDelegate.off();
      return this._domEventDelegate = null;
    }
  },
  publish: function() {
    var root;
    root = this.isRootComponent ? this : this.context.root;
    if (0 < root._pubsub.listeners(arguments[0]).length) {
      return root._pubsub.emit.apply(root._pubsub, arguments);
    } else if (!this.isTopLevelRootComponent) {
      return root.context.root.publish.apply(this, arguments);
    }
  },
  pub: function() {
    return this.publish.apply(this, arguments);
  },
  find: function(refs) {
    if (refs) {
      return ReactDom.findDOMNode(this.refs[refs]);
    } else {
      return ReactDom.findDOMNode(this);
    }
  },
  getState: function() {
    return this.context.root.state;
  }
};

createSubOptions = function(opts) {
  if (opts.name && !opts.displayName) {
    opts.displayName = opts.name;
  }
  if (!opts.mixins) {
    opts.mixins = [];
  }
  opts.mixins.unshift(subComponent);
  opts._domEventDelegate = null;
  if (!opts.events) {
    opts.events = {};
  }
  if (!opts.templateData) {
    opts.templateData = {};
  }
  if (!opts.render) {
    if (opts.template) {
      opts.render = function() {
        this.templateData.props = this.props;
        this.templateData.state = this.isRootComponent ? this.state : this.context.root.state;
        return this.template(this.templateData);
      };
    } else {
      opts.render = function() {
        return '';
      };
    }
  }
  return opts;
};

createRootOptions = function(opts) {
  opts = createSubOptions(opts);
  opts.isRootComponent = true;
  opts.mixins.unshift(rootComponent);
  opts._pubsub = new EventEmitter();
  opts._pubsub.setMaxListeners(0);
  return opts;
};

module.exports = {
  createRootComponent: function(opts) {
    return React.createClass(createRootOptions(opts));
  },
  createSubComponent: function(opts) {
    return React.createClass(createSubOptions(opts));
  },
  render: function(container, component, props) {
    if (props == null) {
      props = null;
    }
    if ('[object String]' === Object.prototype.toString.call(container)) {
      container = document.querySelector(container);
    }
    return ReactDom.render(React.createElement(component, props), container);
  },
  renderToString: function(component, props, state) {
    var _element, element;
    if (props == null) {
      props = null;
    }
    if (state == null) {
      state = null;
    }
    if (React.isValidElement(component)) {
      element = component;
    } else {
      element = React.createElement(component, props);
      if (!component.prototype.isRootComponent || state !== null) {
        _element = element;
        element = React.createElement(React.createClass(createRootOptions({
          getInitialState: function() {
            return state;
          },
          render: function() {
            return React.createElement('div', null, _element);
          }
        })));
      }
    }
    return ReactDomServer.renderToString(element);
  }
};
